


name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start the server
        shell: pwsh
        run: |
          echo "Starting server..."
          Start-Process -NoNewWindow -FilePath "node" -ArgumentList "index.js"
          Start-Sleep -Seconds 5  # Wait for the server to start

      - name: Run the test script
        run: node test.js